// Code generated by pigeon; DO NOT EDIT.

package parser

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"time"
	"unicode"
	"unicode/utf8"
)

type TimeUnit uint32

const (
	TimeUnitSecond TimeUnit = iota
	TimeUnitMinute
	TimeUnitHour
	TimeUnitDay
	TimeUnitWeek
	TimeUnitMonth
	TimeUnitYear
)

type Projection uint32

const (
	ProjectionPast Projection = iota
	ProjectionFuture
)

type TimeOffset struct {
	Projection Projection
	TimeUnit   TimeUnit
	Number     int64
}

func (to TimeOffset) Apply(t time.Time) time.Time {
	// Determine the sign of the offset.
	sign := int64(-1)
	if to.Projection == ProjectionFuture {
		sign = int64(1)
	}

	// Apply the offset.
	switch to.TimeUnit {
	case TimeUnitSecond:
		return t.Add(time.Duration(sign*to.Number) * time.Second)
	case TimeUnitMinute:
		return t.Add(time.Duration(sign*to.Number) * time.Minute)
	case TimeUnitHour:
		return t.Add(time.Duration(sign*to.Number) * time.Hour)
	case TimeUnitDay:
		return t.AddDate(0, 0, int(sign*to.Number))
	case TimeUnitWeek:
		return t.AddDate(0, 0, 7*int(sign*to.Number))
	case TimeUnitMonth:
		return t.AddDate(0, int(sign*to.Number), 0)
	case TimeUnitYear:
		return t.AddDate(int(sign*to.Number), 0, 0)
	}

	return t
}

// Clock is an interface for getting the current time.
type Clock interface {
	Now() time.Time
}

type realClock struct{}

func (realClock) Now() time.Time {
	return time.Now().UTC()
}

// Default clock implementation.
var clock Clock = &realClock{}

// SetClock sets the clock implementation.
func SetClock(c Clock) {
	clock = c
}

var g = &grammar{
	rules: []*rule{
		{
			name: "Input",
			pos:  position{line: 78, col: 1, offset: 1561},
			expr: &actionExpr{
				pos: position{line: 79, col: 5, offset: 1575},
				run: (*parser).callonInput1,
				expr: &seqExpr{
					pos: position{line: 79, col: 5, offset: 1575},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 79, col: 5, offset: 1575},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 79, col: 10, offset: 1580},
								name: "Expression",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 79, col: 21, offset: 1591},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Expression",
			pos:  position{line: 83, col: 1, offset: 1631},
			expr: &choiceExpr{
				pos: position{line: 84, col: 5, offset: 1650},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 84, col: 5, offset: 1650},
						run: (*parser).callonExpression2,
						expr: &labeledExpr{
							pos:   position{line: 84, col: 5, offset: 1650},
							label: "ts",
							expr: &ruleRefExpr{
								pos:  position{line: 84, col: 8, offset: 1653},
								name: "Timestamp",
							},
						},
					},
					&actionExpr{
						pos: position{line: 87, col: 7, offset: 1743},
						run: (*parser).callonExpression5,
						expr: &litMatcher{
							pos:        position{line: 87, col: 7, offset: 1743},
							val:        "now",
							ignoreCase: false,
							want:       "\"now\"",
						},
					},
					&actionExpr{
						pos: position{line: 90, col: 7, offset: 1795},
						run: (*parser).callonExpression7,
						expr: &litMatcher{
							pos:        position{line: 90, col: 7, offset: 1795},
							val:        "today",
							ignoreCase: false,
							want:       "\"today\"",
						},
					},
					&actionExpr{
						pos: position{line: 93, col: 7, offset: 1874},
						run: (*parser).callonExpression9,
						expr: &litMatcher{
							pos:        position{line: 93, col: 7, offset: 1874},
							val:        "yesterday",
							ignoreCase: false,
							want:       "\"yesterday\"",
						},
					},
					&actionExpr{
						pos: position{line: 96, col: 7, offset: 1978},
						run: (*parser).callonExpression11,
						expr: &litMatcher{
							pos:        position{line: 96, col: 7, offset: 1978},
							val:        "tomorrow",
							ignoreCase: false,
							want:       "\"tomorrow\"",
						},
					},
					&actionExpr{
						pos: position{line: 99, col: 7, offset: 2080},
						run: (*parser).callonExpression13,
						expr: &labeledExpr{
							pos:   position{line: 99, col: 7, offset: 2080},
							label: "rt",
							expr: &ruleRefExpr{
								pos:  position{line: 99, col: 10, offset: 2083},
								name: "RelativeTime",
							},
						},
					},
					&actionExpr{
						pos: position{line: 102, col: 7, offset: 2133},
						run: (*parser).callonExpression16,
						expr: &seqExpr{
							pos: position{line: 102, col: 7, offset: 2133},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 102, col: 7, offset: 2133},
									val:        "next",
									ignoreCase: false,
									want:       "\"next\"",
								},
								&ruleRefExpr{
									pos:  position{line: 102, col: 14, offset: 2140},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 102, col: 16, offset: 2142},
									label: "number",
									expr: &zeroOrOneExpr{
										pos: position{line: 102, col: 23, offset: 2149},
										expr: &ruleRefExpr{
											pos:  position{line: 102, col: 24, offset: 2150},
											name: "Number",
										},
									},
								},
								&ruleRefExpr{
									pos:  position{line: 102, col: 33, offset: 2159},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 102, col: 35, offset: 2161},
									label: "timeUnit",
									expr: &ruleRefExpr{
										pos:  position{line: 102, col: 44, offset: 2170},
										name: "TimeUnit",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 115, col: 7, offset: 2449},
						run: (*parser).callonExpression26,
						expr: &seqExpr{
							pos: position{line: 115, col: 7, offset: 2449},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 115, col: 7, offset: 2449},
									val:        "last",
									ignoreCase: false,
									want:       "\"last\"",
								},
								&ruleRefExpr{
									pos:  position{line: 115, col: 14, offset: 2456},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 115, col: 16, offset: 2458},
									label: "number",
									expr: &zeroOrOneExpr{
										pos: position{line: 115, col: 23, offset: 2465},
										expr: &ruleRefExpr{
											pos:  position{line: 115, col: 24, offset: 2466},
											name: "Number",
										},
									},
								},
								&ruleRefExpr{
									pos:  position{line: 115, col: 33, offset: 2475},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 115, col: 35, offset: 2477},
									label: "timeUnit",
									expr: &ruleRefExpr{
										pos:  position{line: 115, col: 44, offset: 2486},
										name: "TimeUnit",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "RelativeTime",
			pos:  position{line: 129, col: 1, offset: 2758},
			expr: &actionExpr{
				pos: position{line: 130, col: 5, offset: 2779},
				run: (*parser).callonRelativeTime1,
				expr: &seqExpr{
					pos: position{line: 130, col: 5, offset: 2779},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 130, col: 5, offset: 2779},
							label: "number",
							expr: &ruleRefExpr{
								pos:  position{line: 130, col: 12, offset: 2786},
								name: "Number",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 130, col: 19, offset: 2793},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 130, col: 21, offset: 2795},
							label: "timeUnit",
							expr: &ruleRefExpr{
								pos:  position{line: 130, col: 30, offset: 2804},
								name: "TimeUnit",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 130, col: 39, offset: 2813},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 130, col: 41, offset: 2815},
							label: "direction",
							expr: &ruleRefExpr{
								pos:  position{line: 130, col: 51, offset: 2825},
								name: "OffsetDirection",
							},
						},
					},
				},
			},
		},
		{
			name: "Number",
			pos:  position{line: 142, col: 1, offset: 3065},
			expr: &actionExpr{
				pos: position{line: 143, col: 5, offset: 3080},
				run: (*parser).callonNumber1,
				expr: &oneOrMoreExpr{
					pos: position{line: 143, col: 5, offset: 3080},
					expr: &charClassMatcher{
						pos:             position{line: 143, col: 5, offset: 3080},
						val:             "[0-9]",
						ranges:          []rune{'0', '9'},
						basicLatinChars: [128]bool{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
						ignoreCase:      false,
						inverted:        false,
					},
				},
			},
		},
		{
			name: "TimeUnit",
			pos:  position{line: 147, col: 1, offset: 3152},
			expr: &choiceExpr{
				pos: position{line: 148, col: 5, offset: 3169},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 148, col: 5, offset: 3169},
						run: (*parser).callonTimeUnit2,
						expr: &ruleRefExpr{
							pos:  position{line: 148, col: 5, offset: 3169},
							name: "SecondUnit",
						},
					},
					&actionExpr{
						pos: position{line: 151, col: 7, offset: 3229},
						run: (*parser).callonTimeUnit4,
						expr: &ruleRefExpr{
							pos:  position{line: 151, col: 7, offset: 3229},
							name: "MonthUnit",
						},
					},
					&actionExpr{
						pos: position{line: 154, col: 7, offset: 3287},
						run: (*parser).callonTimeUnit6,
						expr: &ruleRefExpr{
							pos:  position{line: 154, col: 7, offset: 3287},
							name: "MinuteUnit",
						},
					},
					&actionExpr{
						pos: position{line: 157, col: 7, offset: 3347},
						run: (*parser).callonTimeUnit8,
						expr: &ruleRefExpr{
							pos:  position{line: 157, col: 7, offset: 3347},
							name: "HourUnit",
						},
					},
					&actionExpr{
						pos: position{line: 160, col: 7, offset: 3403},
						run: (*parser).callonTimeUnit10,
						expr: &ruleRefExpr{
							pos:  position{line: 160, col: 7, offset: 3403},
							name: "DayUnit",
						},
					},
					&actionExpr{
						pos: position{line: 163, col: 7, offset: 3457},
						run: (*parser).callonTimeUnit12,
						expr: &ruleRefExpr{
							pos:  position{line: 163, col: 7, offset: 3457},
							name: "WeekUnit",
						},
					},
					&actionExpr{
						pos: position{line: 166, col: 7, offset: 3513},
						run: (*parser).callonTimeUnit14,
						expr: &ruleRefExpr{
							pos:  position{line: 166, col: 7, offset: 3513},
							name: "YearUnit",
						},
					},
				},
			},
		},
		{
			name: "SecondUnit",
			pos:  position{line: 170, col: 1, offset: 3564},
			expr: &choiceExpr{
				pos: position{line: 170, col: 15, offset: 3578},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 170, col: 15, offset: 3578},
						val:        "seconds",
						ignoreCase: false,
						want:       "\"seconds\"",
					},
					&litMatcher{
						pos:        position{line: 170, col: 27, offset: 3590},
						val:        "second",
						ignoreCase: false,
						want:       "\"second\"",
					},
					&litMatcher{
						pos:        position{line: 170, col: 38, offset: 3601},
						val:        "sec",
						ignoreCase: false,
						want:       "\"sec\"",
					},
					&litMatcher{
						pos:        position{line: 170, col: 46, offset: 3609},
						val:        "s",
						ignoreCase: false,
						want:       "\"s\"",
					},
				},
			},
		},
		{
			name: "MinuteUnit",
			pos:  position{line: 171, col: 1, offset: 3613},
			expr: &choiceExpr{
				pos: position{line: 171, col: 15, offset: 3627},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 171, col: 15, offset: 3627},
						val:        "minutes",
						ignoreCase: false,
						want:       "\"minutes\"",
					},
					&litMatcher{
						pos:        position{line: 171, col: 27, offset: 3639},
						val:        "minute",
						ignoreCase: false,
						want:       "\"minute\"",
					},
					&litMatcher{
						pos:        position{line: 171, col: 38, offset: 3650},
						val:        "min",
						ignoreCase: false,
						want:       "\"min\"",
					},
					&litMatcher{
						pos:        position{line: 171, col: 46, offset: 3658},
						val:        "m",
						ignoreCase: false,
						want:       "\"m\"",
					},
				},
			},
		},
		{
			name: "HourUnit",
			pos:  position{line: 172, col: 1, offset: 3662},
			expr: &choiceExpr{
				pos: position{line: 172, col: 13, offset: 3674},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 172, col: 13, offset: 3674},
						val:        "hours",
						ignoreCase: false,
						want:       "\"hours\"",
					},
					&litMatcher{
						pos:        position{line: 172, col: 23, offset: 3684},
						val:        "hour",
						ignoreCase: false,
						want:       "\"hour\"",
					},
					&litMatcher{
						pos:        position{line: 172, col: 32, offset: 3693},
						val:        "hr",
						ignoreCase: false,
						want:       "\"hr\"",
					},
					&litMatcher{
						pos:        position{line: 172, col: 39, offset: 3700},
						val:        "h",
						ignoreCase: false,
						want:       "\"h\"",
					},
				},
			},
		},
		{
			name: "DayUnit",
			pos:  position{line: 173, col: 1, offset: 3704},
			expr: &choiceExpr{
				pos: position{line: 173, col: 12, offset: 3715},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 173, col: 12, offset: 3715},
						val:        "days",
						ignoreCase: false,
						want:       "\"days\"",
					},
					&litMatcher{
						pos:        position{line: 173, col: 21, offset: 3724},
						val:        "day",
						ignoreCase: false,
						want:       "\"day\"",
					},
					&litMatcher{
						pos:        position{line: 173, col: 29, offset: 3732},
						val:        "d",
						ignoreCase: false,
						want:       "\"d\"",
					},
				},
			},
		},
		{
			name: "WeekUnit",
			pos:  position{line: 174, col: 1, offset: 3736},
			expr: &choiceExpr{
				pos: position{line: 174, col: 13, offset: 3748},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 174, col: 13, offset: 3748},
						val:        "weeks",
						ignoreCase: false,
						want:       "\"weeks\"",
					},
					&litMatcher{
						pos:        position{line: 174, col: 23, offset: 3758},
						val:        "week",
						ignoreCase: false,
						want:       "\"week\"",
					},
					&litMatcher{
						pos:        position{line: 174, col: 32, offset: 3767},
						val:        "w",
						ignoreCase: false,
						want:       "\"w\"",
					},
				},
			},
		},
		{
			name: "MonthUnit",
			pos:  position{line: 175, col: 1, offset: 3771},
			expr: &choiceExpr{
				pos: position{line: 175, col: 14, offset: 3784},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 175, col: 14, offset: 3784},
						val:        "months",
						ignoreCase: false,
						want:       "\"months\"",
					},
					&litMatcher{
						pos:        position{line: 175, col: 25, offset: 3795},
						val:        "month",
						ignoreCase: false,
						want:       "\"month\"",
					},
					&litMatcher{
						pos:        position{line: 175, col: 35, offset: 3805},
						val:        "M",
						ignoreCase: false,
						want:       "\"M\"",
					},
				},
			},
		},
		{
			name: "YearUnit",
			pos:  position{line: 176, col: 1, offset: 3809},
			expr: &choiceExpr{
				pos: position{line: 176, col: 13, offset: 3821},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 176, col: 13, offset: 3821},
						val:        "years",
						ignoreCase: false,
						want:       "\"years\"",
					},
					&litMatcher{
						pos:        position{line: 176, col: 23, offset: 3831},
						val:        "year",
						ignoreCase: false,
						want:       "\"year\"",
					},
					&litMatcher{
						pos:        position{line: 176, col: 32, offset: 3840},
						val:        "y",
						ignoreCase: false,
						want:       "\"y\"",
					},
				},
			},
		},
		{
			name: "OffsetDirection",
			pos:  position{line: 177, col: 1, offset: 3844},
			expr: &choiceExpr{
				pos: position{line: 178, col: 5, offset: 3868},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 178, col: 5, offset: 3868},
						run: (*parser).callonOffsetDirection2,
						expr: &litMatcher{
							pos:        position{line: 178, col: 5, offset: 3868},
							val:        "ago",
							ignoreCase: false,
							want:       "\"ago\"",
						},
					},
					&actionExpr{
						pos: position{line: 181, col: 7, offset: 3925},
						run: (*parser).callonOffsetDirection4,
						expr: &litMatcher{
							pos:        position{line: 181, col: 7, offset: 3925},
							val:        "sooner",
							ignoreCase: false,
							want:       "\"sooner\"",
						},
					},
					&actionExpr{
						pos: position{line: 184, col: 7, offset: 3983},
						run: (*parser).callonOffsetDirection6,
						expr: &litMatcher{
							pos:        position{line: 184, col: 7, offset: 3983},
							val:        "later",
							ignoreCase: false,
							want:       "\"later\"",
						},
					},
				},
			},
		},
		{
			name: "Timestamp",
			pos:  position{line: 188, col: 1, offset: 4037},
			expr: &seqExpr{
				pos: position{line: 188, col: 14, offset: 4050},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 188, col: 14, offset: 4050},
						name: "Date",
					},
					&litMatcher{
						pos:        position{line: 188, col: 19, offset: 4055},
						val:        "T",
						ignoreCase: false,
						want:       "\"T\"",
					},
					&ruleRefExpr{
						pos:  position{line: 188, col: 23, offset: 4059},
						name: "Time",
					},
					&litMatcher{
						pos:        position{line: 188, col: 28, offset: 4064},
						val:        "Z",
						ignoreCase: false,
						want:       "\"Z\"",
					},
				},
			},
		},
		{
			name: "Date",
			pos:  position{line: 190, col: 1, offset: 4069},
			expr: &seqExpr{
				pos: position{line: 190, col: 9, offset: 4077},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 190, col: 9, offset: 4077},
						name: "Year",
					},
					&litMatcher{
						pos:        position{line: 190, col: 14, offset: 4082},
						val:        "-",
						ignoreCase: false,
						want:       "\"-\"",
					},
					&ruleRefExpr{
						pos:  position{line: 190, col: 18, offset: 4086},
						name: "Month",
					},
					&litMatcher{
						pos:        position{line: 190, col: 24, offset: 4092},
						val:        "-",
						ignoreCase: false,
						want:       "\"-\"",
					},
					&ruleRefExpr{
						pos:  position{line: 190, col: 28, offset: 4096},
						name: "Day",
					},
				},
			},
		},
		{
			name: "Year",
			pos:  position{line: 192, col: 1, offset: 4101},
			expr: &seqExpr{
				pos: position{line: 192, col: 9, offset: 4109},
				exprs: []any{
					&charClassMatcher{
						pos:             position{line: 192, col: 9, offset: 4109},
						val:             "[0-9]",
						ranges:          []rune{'0', '9'},
						basicLatinChars: [128]bool{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
						ignoreCase:      false,
						inverted:        false,
					},
					&charClassMatcher{
						pos:             position{line: 192, col: 14, offset: 4114},
						val:             "[0-9]",
						ranges:          []rune{'0', '9'},
						basicLatinChars: [128]bool{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
						ignoreCase:      false,
						inverted:        false,
					},
					&charClassMatcher{
						pos:             position{line: 192, col: 19, offset: 4119},
						val:             "[0-9]",
						ranges:          []rune{'0', '9'},
						basicLatinChars: [128]bool{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
						ignoreCase:      false,
						inverted:        false,
					},
					&charClassMatcher{
						pos:             position{line: 192, col: 24, offset: 4124},
						val:             "[0-9]",
						ranges:          []rune{'0', '9'},
						basicLatinChars: [128]bool{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
						ignoreCase:      false,
						inverted:        false,
					},
				},
			},
		},
		{
			name: "Month",
			pos:  position{line: 194, col: 1, offset: 4131},
			expr: &seqExpr{
				pos: position{line: 194, col: 10, offset: 4140},
				exprs: []any{
					&charClassMatcher{
						pos:             position{line: 194, col: 10, offset: 4140},
						val:             "[0-9]",
						ranges:          []rune{'0', '9'},
						basicLatinChars: [128]bool{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
						ignoreCase:      false,
						inverted:        false,
					},
					&charClassMatcher{
						pos:             position{line: 194, col: 15, offset: 4145},
						val:             "[0-9]",
						ranges:          []rune{'0', '9'},
						basicLatinChars: [128]bool{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
						ignoreCase:      false,
						inverted:        false,
					},
				},
			},
		},
		{
			name: "Day",
			pos:  position{line: 196, col: 1, offset: 4152},
			expr: &seqExpr{
				pos: position{line: 196, col: 8, offset: 4159},
				exprs: []any{
					&charClassMatcher{
						pos:             position{line: 196, col: 8, offset: 4159},
						val:             "[0-9]",
						ranges:          []rune{'0', '9'},
						basicLatinChars: [128]bool{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
						ignoreCase:      false,
						inverted:        false,
					},
					&charClassMatcher{
						pos:             position{line: 196, col: 13, offset: 4164},
						val:             "[0-9]",
						ranges:          []rune{'0', '9'},
						basicLatinChars: [128]bool{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
						ignoreCase:      false,
						inverted:        false,
					},
				},
			},
		},
		{
			name: "Time",
			pos:  position{line: 198, col: 1, offset: 4171},
			expr: &seqExpr{
				pos: position{line: 198, col: 9, offset: 4179},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 198, col: 9, offset: 4179},
						name: "Hour",
					},
					&litMatcher{
						pos:        position{line: 198, col: 14, offset: 4184},
						val:        ":",
						ignoreCase: false,
						want:       "\":\"",
					},
					&ruleRefExpr{
						pos:  position{line: 198, col: 18, offset: 4188},
						name: "Minute",
					},
					&litMatcher{
						pos:        position{line: 198, col: 25, offset: 4195},
						val:        ":",
						ignoreCase: false,
						want:       "\":\"",
					},
					&ruleRefExpr{
						pos:  position{line: 198, col: 29, offset: 4199},
						name: "Second",
					},
				},
			},
		},
		{
			name: "Hour",
			pos:  position{line: 200, col: 1, offset: 4207},
			expr: &seqExpr{
				pos: position{line: 200, col: 9, offset: 4215},
				exprs: []any{
					&charClassMatcher{
						pos:             position{line: 200, col: 9, offset: 4215},
						val:             "[0-9]",
						ranges:          []rune{'0', '9'},
						basicLatinChars: [128]bool{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
						ignoreCase:      false,
						inverted:        false,
					},
					&charClassMatcher{
						pos:             position{line: 200, col: 14, offset: 4220},
						val:             "[0-9]",
						ranges:          []rune{'0', '9'},
						basicLatinChars: [128]bool{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
						ignoreCase:      false,
						inverted:        false,
					},
				},
			},
		},
		{
			name: "Minute",
			pos:  position{line: 202, col: 1, offset: 4227},
			expr: &seqExpr{
				pos: position{line: 202, col: 11, offset: 4237},
				exprs: []any{
					&charClassMatcher{
						pos:             position{line: 202, col: 11, offset: 4237},
						val:             "[0-9]",
						ranges:          []rune{'0', '9'},
						basicLatinChars: [128]bool{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
						ignoreCase:      false,
						inverted:        false,
					},
					&charClassMatcher{
						pos:             position{line: 202, col: 16, offset: 4242},
						val:             "[0-9]",
						ranges:          []rune{'0', '9'},
						basicLatinChars: [128]bool{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
						ignoreCase:      false,
						inverted:        false,
					},
				},
			},
		},
		{
			name: "Second",
			pos:  position{line: 204, col: 1, offset: 4249},
			expr: &seqExpr{
				pos: position{line: 204, col: 11, offset: 4259},
				exprs: []any{
					&charClassMatcher{
						pos:             position{line: 204, col: 11, offset: 4259},
						val:             "[0-9]",
						ranges:          []rune{'0', '9'},
						basicLatinChars: [128]bool{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
						ignoreCase:      false,
						inverted:        false,
					},
					&charClassMatcher{
						pos:             position{line: 204, col: 16, offset: 4264},
						val:             "[0-9]",
						ranges:          []rune{'0', '9'},
						basicLatinChars: [128]bool{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
						ignoreCase:      false,
						inverted:        false,
					},
				},
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 206, col: 1, offset: 4271},
			expr: &zeroOrMoreExpr{
				pos: position{line: 206, col: 19, offset: 4289},
				expr: &charClassMatcher{
					pos:             position{line: 206, col: 19, offset: 4289},
					val:             "[ \\t\\n\\r]",
					chars:           []rune{' ', '\t', '\n', '\r'},
					basicLatinChars: [128]bool{false, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
					ignoreCase:      false,
					inverted:        false,
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 208, col: 1, offset: 4301},
			expr: &notExpr{
				pos: position{line: 208, col: 8, offset: 4308},
				expr: &anyMatcher{
					line: 208, col: 9, offset: 4309,
				},
			},
		},
	},
}

func (c *current) onInput1(expr any) (any, error) {

	return expr, nil

}

func (p *parser) callonInput1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInput1(stack["expr"])
}

func (c *current) onExpression2(ts any) (any, error) {
	return time.Parse("2006-01-02T15:04:05Z", string(c.text))

}

func (p *parser) callonExpression2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpression2(stack["ts"])
}

func (c *current) onExpression5() (any, error) {
	return clock.Now(), nil

}

func (p *parser) callonExpression5() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpression5()
}

func (c *current) onExpression7() (any, error) {
	return clock.Now().Truncate(24 * time.Hour), nil

}

func (p *parser) callonExpression7() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpression7()
}

func (c *current) onExpression9() (any, error) {
	return clock.Now().Truncate(24 * time.Hour).Add(-24 * time.Hour), nil

}

func (p *parser) callonExpression9() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpression9()
}

func (c *current) onExpression11() (any, error) {
	return clock.Now().Truncate(24 * time.Hour).Add(24 * time.Hour), nil

}

func (p *parser) callonExpression11() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpression11()
}

func (c *current) onExpression13(rt any) (any, error) {
	return rt, nil

}

func (p *parser) callonExpression13() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpression13(stack["rt"])
}

func (c *current) onExpression16(number, timeUnit any) (any, error) {
	n := int64(1)
	if number != nil {
		n = number.(int64)
	}
	t := timeUnit.(TimeUnit)

	return TimeOffset{
		Projection: ProjectionFuture,
		TimeUnit:   t,
		Number:     n,
	}, nil

}

func (p *parser) callonExpression16() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpression16(stack["number"], stack["timeUnit"])
}

func (c *current) onExpression26(number, timeUnit any) (any, error) {
	n := int64(1)
	if number != nil {
		n = number.(int64)
	}
	t := timeUnit.(TimeUnit)

	return TimeOffset{
		Projection: ProjectionPast,
		TimeUnit:   t,
		Number:     n,
	}, nil

}

func (p *parser) callonExpression26() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpression26(stack["number"], stack["timeUnit"])
}

func (c *current) onRelativeTime1(number, timeUnit, direction any) (any, error) {
	n := number.(int64)
	t := timeUnit.(TimeUnit)
	d := direction.(Projection)

	return TimeOffset{
		Projection: d,
		TimeUnit:   t,
		Number:     n,
	}, nil

}

func (p *parser) callonRelativeTime1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRelativeTime1(stack["number"], stack["timeUnit"], stack["direction"])
}

func (c *current) onNumber1() (any, error) {
	return strconv.ParseInt(string(c.text), 10, 64)

}

func (p *parser) callonNumber1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumber1()
}

func (c *current) onTimeUnit2() (any, error) {
	return TimeUnitSecond, nil

}

func (p *parser) callonTimeUnit2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTimeUnit2()
}

func (c *current) onTimeUnit4() (any, error) {
	return TimeUnitMonth, nil

}

func (p *parser) callonTimeUnit4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTimeUnit4()
}

func (c *current) onTimeUnit6() (any, error) {
	return TimeUnitMinute, nil

}

func (p *parser) callonTimeUnit6() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTimeUnit6()
}

func (c *current) onTimeUnit8() (any, error) {
	return TimeUnitHour, nil

}

func (p *parser) callonTimeUnit8() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTimeUnit8()
}

func (c *current) onTimeUnit10() (any, error) {
	return TimeUnitDay, nil

}

func (p *parser) callonTimeUnit10() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTimeUnit10()
}

func (c *current) onTimeUnit12() (any, error) {
	return TimeUnitWeek, nil

}

func (p *parser) callonTimeUnit12() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTimeUnit12()
}

func (c *current) onTimeUnit14() (any, error) {
	return TimeUnitYear, nil

}

func (p *parser) callonTimeUnit14() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTimeUnit14()
}

func (c *current) onOffsetDirection2() (any, error) {
	return ProjectionPast, nil

}

func (p *parser) callonOffsetDirection2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOffsetDirection2()
}

func (c *current) onOffsetDirection4() (any, error) {
	return ProjectionPast, nil

}

func (p *parser) callonOffsetDirection4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOffsetDirection4()
}

func (c *current) onOffsetDirection6() (any, error) {
	return ProjectionFuture, nil

}

func (p *parser) callonOffsetDirection6() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOffsetDirection6()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	var (
		val any
		ok  bool
	)

	val, ok = p.parseRule(rule)

	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	val, ok := p.parseExpr(expr)

	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}

		val = actVal
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	pt := p.pt
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	cur := p.pt.rn
	start := p.pt

	if cur < 128 {
		if chr.basicLatinChars[cur] != chr.inverted {
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			return val, ok
		}
	}
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	pt := p.pt
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
